[project]
name = "rio-frontend"
description = "Rio Frontend Code In pure Python!"
version = "2025.0.1"
requires-python = ">= 3.11"
readme = {file = "README.txt", content-type = "text/markdown"}
license = "GPL-3.0-or-later"
